<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: huyle
 * Date: Sat, 01 Oct 2016 12:12:42 +0700
 */

$conf['title'] = 'Notes';
$conf['start'] = 'balvenie';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink';
$conf['notify'] = 'hule@apm.com';
$conf['registernotify'] = 'anhhuy@live.com';
$conf['mailfrom'] = 'anhhuy@live.com';
$conf['plugin']['smtp']['smtp_host'] = 'smtp.live.com';
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'anhhuy@live.com';
$conf['plugin']['smtp']['auth_pass'] = 'MYai6NUG';
$conf['plugin']['authpdo']['update-user-info'] = 'VietNam';
$conf['plugin']['skype']['function'] = 'chat';
$conf['plugin']['discussion']['moderatorsnotify'] = '1';

// end auto-generated content
